export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const CREATE_CATEGORY_CHILD = 'CREATE_CATEGORY_CHILD';
export const UPDATE_CATEGORY_CHILD = 'UPDATE_CATEGORY_CHILD';
export const DELETE_CATEGORY_CHILD = 'DELETE_CATEGORY_CHILD';
